version: '3.7'
services:
  web:
    build: ./todolist
    command: python manage.py runserver 0.0.0.0:8000
    volumes:    
      - ./todolist/:/home/kalacey412/Workspace/1.Study/5.OOP/Todo/Todo/todolist
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/12/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=NewPass
      - POSTGRES_DB=test_db
volumes:
  postgres_data: