# Generated by Django 3.2.3 on 2021-05-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210528_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(blank=True, to='base.TaskTags'),
        ),
    ]
