# Generated by Django 3.2.3 on 2021-05-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktags',
            options={'ordering': ['title']},
        ),
    ]
