# Generated by Django 3.2.3 on 2021-06-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_tasktags_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='base.TaskTags'),
        ),
    ]
